import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { UIProvider } from "./providers/UIProvider";
import "./globals.css";

import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Simple blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UIProvider>
          <main>
            <Navbar />
            <div className="wrapper">
              <div className="content">{children}</div>
            </div>
            <Footer />
          </main>
        </UIProvider>
      </body>
    </html>
  );
}
